### ISSUE TITLE
Mask not applied & PicklingError

### ISSUE THREAD

**Issue by Karol-G** [sraashis/deepdyn#247]
Hi again,

I tried to run the main.py but the logs do not look good...

<details><summary>**Click to open run log**</summary>
<p>

> 
	Total Params: 1864322
	Total Params: 31042434
	### SPLIT FOUND:  data\STARE\splits\STARE_0.json Loaded
	### Mask not applied.  im0077.ppm
	### Mask not applied.  im0081.ppm
	### Mask not applied.  im0236.ppm
	### Mask not applied.  im0255.ppm
	### Mask not applied.  im0005.ppm
	### Mask not applied.  im0003.ppm
	### Mask not applied.  im0235.ppm
	### Mask not applied.  im0139.ppm
	### Mask not applied.  im0319.ppm
	### Mask not applied.  im0001.ppm
	### Mask not applied.  im0163.ppm
	### Mask not applied.  im0044.ppm
	Patches: 144
	### Mask not applied.  im0002.ppm
	Patches: 12
	### Mask not applied.  im0162.ppm
	Patches: 12
	### Mask not applied.  im0291.ppm
	Patches: 12
	### Mask not applied.  im0082.ppm
	Patches: 12
	Training...
	### SPLIT FOUND:  data\STARE\splits\STARE_1.json Loaded
	Traceback (most recent call last):
	  File "C:\Users\Cookie\Documents\GitKraken\deepdyn\testarch\unet\__init__.py", line 52, in run
		epoch_run=trainer.epoch_ce_loss)
	  File "C:\Users\Cookie\Documents\GitKraken\deepdyn\torchtrainer\torchtrainer.py", line 84, in train
		epoch_run(epoch=epoch, data_loader=data_loader, logger=self.train_logger)
	  File "C:\Users\Cookie\Documents\GitKraken\deepdyn\torchtrainer\torchtrainer.py", line 221, in epoch_ce_loss
		for i, data in enumerate(kw['data_loader'], 1):
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
		return _MultiProcessingDataLoaderIter(self)
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__
		w.start()
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\multiprocessing\process.py", line 112, in start
		self._popen = self._Popen(self)
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\multiprocessing\context.py", line 223, in _Popen
		return _default_context.get_context().Process._Popen(process_obj)
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\multiprocessing\context.py", line 322, in _Popen
		return Popen(process_obj)
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
		reduction.dump(process_obj, to_child)
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\multiprocessing\reduction.py", line 60, in dump
		ForkingPickler(file, protocol).dump(obj)
	_pickle.PicklingError: Can't pickle <function <lambda> at 0x000002DA8D01B318>: attribute lookup <lambda> on testarch.unet.runs failed
	### Mask not applied.  im0324.ppm
	### Mask not applied.  im0239.ppm
	### Mask not applied.  im0240.ppm
	### Mask not applied.  im0004.ppm
	### Mask not applied.  im0005.ppm
	### Mask not applied.  im0003.ppm
	### Mask not applied.  im0235.ppm
	### Mask not applied.  im0139.ppm
	### Mask not applied.  im0319.ppm
	### Mask not applied.  im0001.ppm
	### Mask not applied.  im0163.ppm
	### Mask not applied.  im0044.ppm
	Patches: 144
	### Mask not applied.  im0077.ppm
	Patches: 12
	### Mask not applied.  im0081.ppm
	Patches: 12
	### Mask not applied.  im0236.ppm
	Patches: 12
	### Mask not applied.  im0255.ppm
	Patches: 12
	Training...
	Traceback (most recent call last):
	  File "C:\Users\Cookie\Documents\GitKraken\deepdyn\testarch\unet\__init__.py", line 52, in run
		epoch_run=trainer.epoch_ce_loss)
	  File "C:\Users\Cookie\Documents\GitKraken\deepdyn\torchtrainer\torchtrainer.py", line 84, in train
		epoch_run(epoch=epoch, data_loader=data_loader, logger=self.train_logger)
	  File "C:\Users\Cookie\Documents\GitKraken\deepdyn\torchtrainer\torchtrainer.py", line 221, in epoch_ce_loss
		for i, data in enumerate(kw['data_loader'], 1):
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
		return _MultiProcessingDataLoaderIter(self)
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__
		w.start()
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\multiprocessing\process.py", line 112, in start
		self._popen = self._Popen(self)
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\multiprocessing\context.py", line 223, in _Popen
		return _default_context.get_context().Process._Popen(process_obj)
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\multiprocessing\context.py", line 322, in _Popen
		return Popen(process_obj)
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
		reduction.dump(process_obj, to_child)
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\multiprocessing\reduction.py", line 60, in dump
		ForkingPickler(file, protocol).dump(obj)
	_pickle.PicklingError: Can't pickle <function <lambda> at 0x000002DA8D01B318>: attribute lookup <lambda> on testarch.unet.runs failed
	### SPLIT FOUND:  data\STARE\splits\STARE_2.json Loaded
	### Mask not applied.  im0324.ppm
	### Mask not applied.  im0239.ppm
	### Mask not applied.  im0240.ppm
	### Mask not applied.  im0004.ppm
	### Mask not applied.  im0002.ppm
	### Mask not applied.  im0162.ppm
	### Mask not applied.  im0291.ppm
	### Mask not applied.  im0082.ppm
	### Mask not applied.  im0319.ppm
	### Mask not applied.  im0001.ppm
	### Mask not applied.  im0163.ppm
	### Mask not applied.  im0044.ppm
	Patches: 144
	### Mask not applied.  im0005.ppm
	Patches: 12
	### Mask not applied.  im0003.ppm
	Patches: 12
	### Mask not applied.  im0235.ppm
	Patches: 12
	### Mask not applied.  im0139.ppm
	Patches: 12
	Training...
	Traceback (most recent call last):
	  File "C:\Users\Cookie\Documents\GitKraken\deepdyn\testarch\unet\__init__.py", line 52, in run
		epoch_run=trainer.epoch_ce_loss)
	  File "C:\Users\Cookie\Documents\GitKraken\deepdyn\torchtrainer\torchtrainer.py", line 84, in train
		epoch_run(epoch=epoch, data_loader=data_loader, logger=self.train_logger)
	  File "C:\Users\Cookie\Documents\GitKraken\deepdyn\torchtrainer\torchtrainer.py", line 221, in epoch_ce_loss
		for i, data in enumerate(kw['data_loader'], 1):
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
		return _MultiProcessingDataLoaderIter(self)
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__
		w.start()
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\multiprocessing\process.py", line 112, in start
		self._popen = self._Popen(self)
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\multiprocessing\context.py", line 223, in _Popen
		return _default_context.get_context().Process._Popen(process_obj)
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\multiprocessing\context.py", line 322, in _Popen
		return Popen(process_obj)
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
		reduction.dump(process_obj, to_child)
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\multiprocessing\reduction.py", line 60, in dump
		ForkingPickler(file, protocol).dump(obj)
	_pickle.PicklingError: Can't pickle <function <lambda> at 0x000002DA8D01B318>: attribute lookup <lambda> on testarch.unet.runs failed
	### SPLIT FOUND:  data\STARE\splits\STARE_3.json Loaded
	### Mask not applied.  im0324.ppm
	### Mask not applied.  im0239.ppm
	### Mask not applied.  im0240.ppm
	### Mask not applied.  im0004.ppm
	### Mask not applied.  im0002.ppm
	### Mask not applied.  im0162.ppm
	### Mask not applied.  im0291.ppm
	### Mask not applied.  im0082.ppm
	### Mask not applied.  im0077.ppm
	### Mask not applied.  im0081.ppm
	### Mask not applied.  im0236.ppm
	### Mask not applied.  im0255.ppm
	Patches: 144
	### Mask not applied.  im0319.ppm
	Patches: 12
	### Mask not applied.  im0001.ppm
	Patches: 12
	### Mask not applied.  im0163.ppm
	Patches: 12
	### Mask not applied.  im0044.ppm
	Patches: 12
	Training...
	Traceback (most recent call last):
	  File "C:\Users\Cookie\Documents\GitKraken\deepdyn\testarch\unet\__init__.py", line 52, in run
		epoch_run=trainer.epoch_ce_loss)
	  File "C:\Users\Cookie\Documents\GitKraken\deepdyn\torchtrainer\torchtrainer.py", line 84, in train
		epoch_run(epoch=epoch, data_loader=data_loader, logger=self.train_logger)
	  File "C:\Users\Cookie\Documents\GitKraken\deepdyn\torchtrainer\torchtrainer.py", line 221, in epoch_ce_loss
		for i, data in enumerate(kw['data_loader'], 1):
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
		return _MultiProcessingDataLoaderIter(self)
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__
		w.start()
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\multiprocessing\process.py", line 112, in start
		self._popen = self._Popen(self)
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\multiprocessing\context.py", line 223, in _Popen
		return _default_context.get_context().Process._Popen(process_obj)
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\multiprocessing\context.py", line 322, in _Popen
		return Popen(process_obj)
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
		reduction.dump(process_obj, to_child)
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\multiprocessing\reduction.py", line 60, in dump
		ForkingPickler(file, protocol).dump(obj)
	_pickle.PicklingError: Can't pickle <function <lambda> at 0x000002DA8D01B318>: attribute lookup <lambda> on testarch.unet.runs failed
	### SPLIT FOUND:  data\STARE\splits\STARE_4.json Loaded
	Total Params: 1864322
	Total Params: 31042434
	Traceback (most recent call last):
	  File "<string>", line 1, in <module>
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\multiprocessing\spawn.py", line 105, in spawn_main
		exitcode = _main(fd)
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\multiprocessing\spawn.py", line 115, in _main
		self = reduction.pickle.load(from_parent)
	EOFError: Ran out of input
	### Mask not applied.  im0002.ppm
	### Mask not applied.  im0162.ppm
	### Mask not applied.  im0291.ppm
	### Mask not applied.  im0082.ppm
	### Mask not applied.  im0077.ppm
	### Mask not applied.  im0081.ppm
	### Mask not applied.  im0236.ppm
	### Mask not applied.  im0255.ppm
	### Mask not applied.  im0005.ppm
	### Mask not applied.  im0003.ppm
	### Mask not applied.  im0235.ppm
	### Mask not applied.  im0139.ppm
	Patches: 144
	### Mask not applied.  im0324.ppm
	Patches: 12
	### Mask not applied.  im0239.ppm
	Patches: 12
	### Mask not applied.  im0240.ppm
	Patches: 12
	### Mask not applied.  im0004.ppm
	Patches: 12
	Training...
	[0, 0, 0, 0]
	Traceback (most recent call last):
	  File "C:\Users\Cookie\Documents\GitKraken\deepdyn\testarch\unet\__init__.py", line 52, in run
		epoch_run=trainer.epoch_ce_loss)
	  File "C:\Users\Cookie\Documents\GitKraken\deepdyn\torchtrainer\torchtrainer.py", line 84, in train
		epoch_run(epoch=epoch, data_loader=data_loader, logger=self.train_logger)
	  File "C:\Users\Cookie\Documents\GitKraken\deepdyn\torchtrainer\torchtrainer.py", line 221, in epoch_ce_loss
		for i, data in enumerate(kw['data_loader'], 1):
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
		return _MultiProcessingDataLoaderIter(self)
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__
		w.start()
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\multiprocessing\process.py", line 112, in start
		self._popen = self._Popen(self)
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\multiprocessing\context.py", line 223, in _Popen
		return _default_context.get_context().Process._Popen(process_obj)
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\multiprocessing\context.py", line 322, in _Popen
		return Popen(process_obj)
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
		reduction.dump(process_obj, to_child)
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\multiprocessing\reduction.py", line 60, in dump
		ForkingPickler(file, protocol).dump(obj)
	_pickle.PicklingError: Can't pickle <function <lambda> at 0x000002DA8D01B318>: attribute lookup <lambda> on testarch.unet.runs failed
	### SPLIT FOUND:  data\STARE\splits\STARE_0.json Loaded
	### Mask not applied.  im0077.ppm
	Total Params: 1864322
	### SPLIT FOUND:  data\STARE\splits\STARE_1.json Loaded
	Traceback (most recent call last):
	  File "C:\Users\Cookie\Documents\GitKraken\deepdyn\testarch\miniunet\__init__.py", line 42, in run
		mode='train')
	  File "C:\Users\Cookie\Documents\GitKraken\deepdyn\torchtrainer\datagen.py", line 88, in get_loader
		gen = cls(conf=conf, images=images, transforms=transforms, shuffle_indices=True, mode=mode)
	  File "C:\Users\Cookie\Documents\GitKraken\deepdyn\testarch\miniunet\miniunet_dataloader.py", line 29, in __init__
		self._load_indices()
	  File "C:\Users\Cookie\Documents\GitKraken\deepdyn\testarch\miniunet\miniunet_dataloader.py", line 35, in _load_indices
		img_obj = self._get_image_obj(img_file)
	  File "C:\Users\Cookie\Documents\GitKraken\deepdyn\testarch\miniunet\miniunet_dataloader.py", line 60, in _get_image_obj
		self.unet_dir + sep + img_obj.file_name.split('.')[0] + self.input_image_ext, 1)
	  File "C:\Users\Cookie\Documents\GitKraken\deepdyn\utils\img_utils.py", line 186, in get_image_as_array
		img = IMG.open(image_file)
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\site-packages\PIL\Image.py", line 2809, in open
		fp = builtins.open(filename, "rb")
	FileNotFoundError: [Errno 2] No such file or directory: 'logs\\STARE\\UNET_1_100_1\\im0077.png'
	### Mask not applied.  im0324.ppm
	### SPLIT FOUND:  data\STARE\splits\STARE_2.json Loaded
	Traceback (most recent call last):
	  File "C:\Users\Cookie\Documents\GitKraken\deepdyn\testarch\miniunet\__init__.py", line 42, in run
		mode='train')
	  File "C:\Users\Cookie\Documents\GitKraken\deepdyn\torchtrainer\datagen.py", line 88, in get_loader
		gen = cls(conf=conf, images=images, transforms=transforms, shuffle_indices=True, mode=mode)
	  File "C:\Users\Cookie\Documents\GitKraken\deepdyn\testarch\miniunet\miniunet_dataloader.py", line 29, in __init__
		self._load_indices()
	  File "C:\Users\Cookie\Documents\GitKraken\deepdyn\testarch\miniunet\miniunet_dataloader.py", line 35, in _load_indices
		img_obj = self._get_image_obj(img_file)
	  File "C:\Users\Cookie\Documents\GitKraken\deepdyn\testarch\miniunet\miniunet_dataloader.py", line 60, in _get_image_obj
		self.unet_dir + sep + img_obj.file_name.split('.')[0] + self.input_image_ext, 1)
	  File "C:\Users\Cookie\Documents\GitKraken\deepdyn\utils\img_utils.py", line 186, in get_image_as_array
		img = IMG.open(image_file)
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\site-packages\PIL\Image.py", line 2809, in open
		fp = builtins.open(filename, "rb")
	FileNotFoundError: [Errno 2] No such file or directory: 'logs\\STARE\\UNET_1_100_1\\im0324.png'
	Traceback (most recent call last):
	  File "C:\Users\Cookie\Documents\GitKraken\deepdyn\testarch\miniunet\__init__.py", line 42, in run
		mode='train')
	  File "C:\Users\Cookie\Documents\GitKraken\deepdyn\torchtrainer\datagen.py", line 88, in get_loader
		gen = cls(conf=conf, images=images, transforms=transforms, shuffle_indices=True, mode=mode)
	  File "C:\Users\Cookie\Documents\GitKraken\deepdyn\testarch\miniunet\miniunet_dataloader.py", line 29, in __init__
		self._load_indices()
	  File "C:\Users\Cookie\Documents\GitKraken\deepdyn\testarch\miniunet\miniunet_dataloader.py", line 35, in _load_indices
		img_obj = self._get_image_obj(img_file)
	  File "C:\Users\Cookie\Documents\GitKraken\deepdyn\testarch\miniunet\miniunet_dataloader.py", line 60, in _get_image_obj
		self.unet_dir + sep + img_obj.file_name.split('.')[0] + self.input_image_ext, 1)
	  File "C:\Users\Cookie\Documents\GitKraken\deepdyn\utils\img_utils.py", line 186, in get_image_as_array
		img = IMG.open(image_file)
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\site-packages\PIL\Image.py", line 2809, in open
		fp = builtins.open(filename, "rb")
	FileNotFoundError: [Errno 2] No such file or directory: 'logs\\STARE\\UNET_1_100_1\\im0324.png'
	### Mask not applied.  im0324.ppm
	### SPLIT FOUND:  data\STARE\splits\STARE_3.json Loaded
	### Mask not applied.  im0324.ppm
	### SPLIT FOUND:  data\STARE\splits\STARE_4.json Loaded
	Traceback (most recent call last):
	  File "C:\Users\Cookie\Documents\GitKraken\deepdyn\testarch\miniunet\__init__.py", line 42, in run
		mode='train')
	  File "C:\Users\Cookie\Documents\GitKraken\deepdyn\torchtrainer\datagen.py", line 88, in get_loader
		gen = cls(conf=conf, images=images, transforms=transforms, shuffle_indices=True, mode=mode)
	  File "C:\Users\Cookie\Documents\GitKraken\deepdyn\testarch\miniunet\miniunet_dataloader.py", line 29, in __init__
		self._load_indices()
	  File "C:\Users\Cookie\Documents\GitKraken\deepdyn\testarch\miniunet\miniunet_dataloader.py", line 35, in _load_indices
		img_obj = self._get_image_obj(img_file)
	  File "C:\Users\Cookie\Documents\GitKraken\deepdyn\testarch\miniunet\miniunet_dataloader.py", line 60, in _get_image_obj
		self.unet_dir + sep + img_obj.file_name.split('.')[0] + self.input_image_ext, 1)
	  File "C:\Users\Cookie\Documents\GitKraken\deepdyn\utils\img_utils.py", line 186, in get_image_as_array
		img = IMG.open(image_file)
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\site-packages\PIL\Image.py", line 2809, in open
		fp = builtins.open(filename, "rb")
	FileNotFoundError: [Errno 2] No such file or directory: 'logs\\STARE\\UNET_1_100_1\\im0324.png'
	### Mask not applied.  im0002.ppm
	[0, 0, 0, 0]
	### SPLIT FOUND:  data\STARE\splits\STARE_0.json Loaded
	Traceback (most recent call last):
	  File "C:\Users\Cookie\Documents\GitKraken\deepdyn\testarch\miniunet\__init__.py", line 42, in run
		mode='train')
	  File "C:\Users\Cookie\Documents\GitKraken\deepdyn\torchtrainer\datagen.py", line 88, in get_loader
		gen = cls(conf=conf, images=images, transforms=transforms, shuffle_indices=True, mode=mode)
	  File "C:\Users\Cookie\Documents\GitKraken\deepdyn\testarch\miniunet\miniunet_dataloader.py", line 29, in __init__
		self._load_indices()
	  File "C:\Users\Cookie\Documents\GitKraken\deepdyn\testarch\miniunet\miniunet_dataloader.py", line 35, in _load_indices
		img_obj = self._get_image_obj(img_file)
	  File "C:\Users\Cookie\Documents\GitKraken\deepdyn\testarch\miniunet\miniunet_dataloader.py", line 60, in _get_image_obj
		self.unet_dir + sep + img_obj.file_name.split('.')[0] + self.input_image_ext, 1)
	  File "C:\Users\Cookie\Documents\GitKraken\deepdyn\utils\img_utils.py", line 186, in get_image_as_array
		img = IMG.open(image_file)
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\site-packages\PIL\Image.py", line 2809, in open
		fp = builtins.open(filename, "rb")
	FileNotFoundError: [Errno 2] No such file or directory: 'logs\\STARE\\UNET_1_100_1\\im0002.png'
	Total Params: 31042434
	Traceback (most recent call last):
	  File "<string>", line 1, in <module>
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\multiprocessing\spawn.py", line 105, in spawn_main
		exitcode = _main(fd)
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\multiprocessing\spawn.py", line 115, in _main
		self = reduction.pickle.load(from_parent)
	EOFError: Ran out of input
	Total Params: 1864322
	### Mask not applied.  im0077.ppm
	### Mask not applied.  im0081.ppm
	### Mask not applied.  im0236.ppm
	### Mask not applied.  im0255.ppm
	### Mask not applied.  im0005.ppm
	### Mask not applied.  im0003.ppm
	### Mask not applied.  im0235.ppm
	### Mask not applied.  im0139.ppm
	### Mask not applied.  im0319.ppm
	### Mask not applied.  im0001.ppm
	### Mask not applied.  im0163.ppm
	### Mask not applied.  im0044.ppm
	Patches: 144
	### Mask not applied.  im0002.ppm
	Patches: 12
	### Mask not applied.  im0162.ppm
	Patches: 12
	### Mask not applied.  im0291.ppm
	Patches: 12
	### Mask not applied.  im0082.ppm
	Patches: 12
	Training...
	Traceback (most recent call last):
	  File "C:\Users\Cookie\Documents\GitKraken\deepdyn\testarch\unet\__init__.py", line 52, in run
		epoch_run=trainer.epoch_ce_loss)
	  File "C:\Users\Cookie\Documents\GitKraken\deepdyn\torchtrainer\torchtrainer.py", line 84, in train
		epoch_run(epoch=epoch, data_loader=data_loader, logger=self.train_logger)
	  File "C:\Users\Cookie\Documents\GitKraken\deepdyn\torchtrainer\torchtrainer.py", line 221, in epoch_ce_loss
		for i, data in enumerate(kw['data_loader'], 1):
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
		return _MultiProcessingDataLoaderIter(self)
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__
		w.start()
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\multiprocessing\process.py", line 112, in start
		self._popen = self._Popen(self)
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\multiprocessing\context.py", line 223, in _Popen
		return _default_context.get_context().Process._Popen(process_obj)
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\multiprocessing\context.py", line 322, in _Popen
		return Popen(process_obj)
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
		reduction.dump(process_obj, to_child)
	  File "C:\Users\Cookie\Anaconda3\envs\deepdyn\lib\multiprocessing\reduction.py", line 60, in dump
		ForkingPickler(file, protocol).dump(obj)
	_pickle.PicklingError: Can't pickle <function <lambda> at 0x000002DA8D01B318>: attribute lookup <lambda> on testarch.unet.runs failed
	### SPLIT FOUND:  data\STARE\splits\STARE_1.json Loaded

	Process finished with exit code -1

</p>
</details>

I get a lot of warnings regarding:

> Mask not applied

That's probably not very good. 
Furthermore I get a lot of pickle errors:

> _pickle.PicklingError: Can't pickle <function <lambda> at 0x000002DA8D01B318>: attribute lookup <lambda> on testarch.unet.runs failed

Do you know why this could be happening?

Best,
Karol

**Comment by manvirvirk** [comment]
i m getting same error. Did you find any solution to it. Thanks

**Comment by Karol-G** [comment]
No sadly not. But if you should happen to find one, than I would be glad to know :)

**Comment by sraashis** [comment]
Hi all,

Mask not applied is not an error. It is just a warning.  As for the, Can't pickle <function <lambda> at 0x000002DA8D01B318>: I think I know where it is coming from. I will take a look and fix it ASAP.  
As for- No such file or directory: 'logs\\STARE\\UNET_1_100_1\\..., I think this part is for mini-unet. Which means first we need to run U-net and then mini u-net because mini-unet picks up the output of U-net as its input. This can be configured in main.py.

Sorry for the late response.
Thanks,
AK

**Comment by sraashis** [comment]
Hi @Karol-G,
Can you please try again? I just fixed the bug and tested in my machine it is training well. 
Thanks,
AK
